artifcats_root: artifacts

data_ingestion:
  source_url: 'https://drive.google.com/uc?/export=download&id=1RxwbLBQml6c0bqMSPl--6khIYJGznilq'
  root_dir: artifacts/data_ingestion
  zip_file: artifacts/data_ingestion/Satellite_image_classif.zip


base_model_prep:
  root_dir: artifacts/base_model
  base_model_path: artifacts/base_model/base_model.keras

model_trainer:
  root_dir: artifacts/updated_model
  updated_model_path: Model/updated_model.h5 #artifacts/updated_model/updated_model.h5
  data_path: artifacts/data_ingestion/data

model_evaluation:
  root_dir: artifacts/model_evaluation
  eval_path: artifacts/model_evaluation/evaluation.json
  mlflow_uri: 'https://dagshub.com/larakim/ML-pipeline-Satellite-image-classification.mlflow'