artifcats_root: artifacts

data_ingestion:
  source_url: 'https://drive.google.com/uc?/export=download&id=1RxwbLBQml6c0bqMSPl--6khIYJGznilq'
  root_dir: artifacts/data_ingestion
  zip_file: artifacts/data_ingestion/Satellite_image_classif.zip